export const ERROR_CODE_MESSAGES: Record<string, string> = {
  AUTH_TOKEN_MISSING: '請先登入後再試',
  AUTH_TOKEN_INVALID: '請重新登入',
  ADMIN_REQUIRED: '權限不足',
  AUTH_REQUIRED: '請先登入後再試',
  FORBIDDEN: '權限不足',
  USER_NOT_FOUND: '找不到使用者資料',
  FAVORITE_ALREADY_EXISTS: '已經收藏過此活動',
  FAVORITE_NOT_FOUND: '收藏的活動不存在',
  EVENT_NOT_FAVORITABLE: '只有已通過審核的活動可以收藏',
  EVENT_NOT_FOUND: '活動不存在或已被刪除',
  EVENT_EDIT_FORBIDDEN: '沒有權限編輯此活動',
  EVENT_DELETE_FORBIDDEN: '沒有權限刪除此活動',
  EVENT_RESUBMIT_FORBIDDEN: '沒有權限重新送審此活動',
  EVENT_RESUBMIT_INVALID_STATE: '只有已拒絕的活動才能重新送審',
  VENUE_NOT_FOUND: '場地不存在或已被刪除',
  VENUE_HAS_EVENTS: '此場地仍有相關活動，請先刪除相關活動',
  ARTIST_NOT_FOUND: '藝人不存在或已被刪除',
  ARTIST_EDIT_FORBIDDEN: '沒有權限編輯此藝人',
  ARTIST_RESUBMIT_FORBIDDEN: '沒有權限重新送審此藝人',
  ARTIST_RESUBMIT_INVALID_STATE: '只有已拒絕的藝人才能重新送審',
  ARTIST_HAS_EVENTS: '此藝人已有生日應援活動，無法刪除',
  IMAGE_TOO_LARGE: '圖片大小不能超過 5MB',
  IMAGE_UNSUPPORTED_FORMAT: '圖片格式不支援，請使用 JPG、PNG 或 WebP 格式',
  IMAGE_FILE_MISSING: '請選擇要上傳的圖片',
  IMAGE_URL_MISSING: '圖片網址無效',
  IMAGE_URL_INVALID: '圖片網址無效',
  IMAGE_DELETE_FAILED: '圖片刪除失敗，請稍後再試',
  INTERNAL_ERROR: '伺服器發生錯誤，請稍後再試',
  SERVICE_UNAVAILABLE: '服務暫時無法使用，請稍後再試',
  CONTACT_SUBMISSION_FAILED: '聯絡表單送出失敗，請稍後再試',
  PLACES_API_ERROR: '地點搜尋服務暫時無法使用，請稍後再試',
  R2_UNREACHABLE: '圖片服務暫時無法使用，請稍後再試',
  RATE_LIMITED: '請求過於頻繁，請稍後再試',
  ROUTE_NOT_FOUND: '找不到此頁面或資源',
};

export const FIELD_LABELS: Record<string, string> = {
  displayName: '顯示名稱',
  stageName: '藝名',
  title: '活動標題',
  eventId: '活動',
  artistIds: '藝人',
  'location.coordinates': '地點座標',
  limit: '筆數',
  status: '狀態',
};
